---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logrotate
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logrotate
subjects:
- kind: ServiceAccount
  name: logrotate
  namespace: odin
roleRef:
  kind: ClusterRole
  name: logrotate
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nsupdate-record-generator.serviceAccountName" . }}
  labels:
    {{- include "nsupdate-record-generator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
