{{- if .Values.tsigSealedSecrets -}}
{{- range $val := .Values.tsigSealedSecrets }}
{{- if $val.kind }}
{{- if eq $val.kind "SealedSecret" }}
---
{{ toYaml $val }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
